services:

  test:
    build: ./test/
    container_name: test
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - test-db
    restart: unless-stopped

  test-db:
    image: postgres:16
    container_name: test-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - teste_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  test-gateway:
    image: nginx:stable
    container_name: test-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - test
    restart: unless-stopped
  
volumes:
  teste_pgdata: